In [1]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [3]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(s)
print(s['b'])

a    1
b    2
c    3
d    4
e    5
dtype: int64
2


In [4]:
data = [
        [1,2,3,4,5],
        [1,5,2,3,4]
        ]
df = pd.DataFrame(data)
print(df)

   0  1  2  3  4
0  1  2  3  4  5
1  1  5  2  3  4


In [30]:
data = [
        ['Alex',10,'Feb'],
        ['Bob',12,'Feb'],
        ['Clarke',13,'Jan'],
        ['e1',13],
        ['e3',13,'Jan'],
        ['e3',13,'Jan'],
        ['e4',13,'Jan'],
        ['e5',13,'Jan']]
df = pd.DataFrame(data,columns=['Name','Age','month'])

In [31]:
print(df)

     Name  Age month
0    Alex   10   Feb
1     Bob   12   Feb
2  Clarke   13   Jan
3      e1   13  None
4      e3   13   Jan
5      e3   13   Jan
6      e4   13   Jan
7      e5   13   Jan


In [7]:
dfm =df.loc[df['month'] == 'Feb']
print('----------------------------------')
print(dfm)

----------------------------------
   Name  Age month
0  Alex   10   Feb
1   Bob   12   Feb


In [29]:
data ={
     'Name':['Tom', 'Jack', 'Steve', 'Ricky'],
     'Age':[28,34,29,42],
     'month':['jan','feb','feb','feb']
     }
df = pd.DataFrame(data)
print(df)

    Name  Age month
0    Tom   28   jan
1   Jack   34   feb
2  Steve   29   feb
3  Ricky   42   feb


In [9]:
data = [
        {'a': 1, 'b': 2,'d':50},
        {'a': 5, 'b': 10, 'c': 20}
        ]
df1 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b','c','d'])
print (df1)

        a   b     c     d
first   1   2   NaN  50.0
second  5  10  20.0   NaN


In [10]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'c', 'd']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'd', 'c', 'b'])}

df = pd.DataFrame(d)
print(df.head())
print('---------------------')
print (df['one'])

   one  two
a  1.0    1
b  NaN    4
c  2.0    3
d  3.0    2
---------------------
a    1.0
b    NaN
c    2.0
d    3.0
Name: one, dtype: float64


In [11]:
df['three']=pd.Series([10,20,30],index=['a','b','c'])
print(df)

   one  two  three
a  1.0    1   10.0
b  NaN    4   20.0
c  2.0    3   30.0
d  3.0    2    NaN


In [12]:
print ("Deleting the first column using DEL function:")
del df['one']
print (df)

Deleting the first column using DEL function:
   two  three
a    1   10.0
b    4   20.0
c    3   30.0
d    2    NaN


In [33]:
import numpy as np

df = pd.DataFrame(
    np.random.randn(8, 4),
    index = ['a','b','c','d','e','f','g','h'],
     columns = ['A', 'B', 'C', 'D']
     )
print(df)
print('-------------------------------------------------')
#select all rows for a specific column

df2 = df.loc['b':'e',['A','C']]

print (df2)

          A         B         C         D
a -0.860598 -0.651975  0.325410  1.012117
b -0.329511  2.757364  0.077794 -0.532514
c  0.437375  0.041338  1.664334 -0.149520
d  0.907507  1.010655 -0.421335 -1.342246
e  2.402133  0.459222 -0.498248 -0.544410
f -1.458678 -0.026010 -0.825181  0.898445
g -0.300666  1.679827  1.628643 -0.570291
h  0.170178  0.665198  0.715759 -1.004031
-------------------------------------------------
          A         C
b -0.329511  0.077794
c  0.437375  1.664334
d  0.907507 -0.421335
e  2.402133 -0.498248


In [36]:
import pandas as pd
pd.options.plotting.backend = "plotly"
df = pd.DataFrame(dict(a=[1,3,10], b=[3,2,1]))

# using Plotly Express via the Pandas backend
fig1 = df.plot.bar()
fig1.show()

# using Plotly Express directly
import plotly.express as px
fig2 = px.bar(df)
fig2.show()

In [15]:
import plotly.express as px
df = px.data.gapminder().query("year == 2007").query("continent == 'Asia'")
df.loc[df['pop'] < 2.e6, 'country'] = 'Other countries' # Represent only large countries
fig = px.pie(df, values='pop', names='country', title='Population of European continent')
fig.show()

In [16]:
import plotly.graph_objects as go

labels = ['Jan','Feb']
values = [15, 10 ]

fig = go.Figure(data=[go.Pie(labels=labels, values=values)])
fig.show()

In [17]:
import numpy as np 

a = [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
a2 = [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
npa= np.array(a)
npa2= np.array(a2)

In [39]:
print(np.shape(npa2))

(3, 5)


In [18]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [19]:
a = np.zeros((3,3,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [20]:
b= np.random.rand(5,3)
print(b)
print('---------------------------')
b = np.sort(b)
print(b)

[[0.43878222 0.60205151 0.81325559]
 [0.32817655 0.22772432 0.01555355]
 [0.7537378  0.65833778 0.83135812]
 [0.32962358 0.8769639  0.2857884 ]
 [0.78383444 0.62906002 0.95554699]]
---------------------------
[[0.43878222 0.60205151 0.81325559]
 [0.01555355 0.22772432 0.32817655]
 [0.65833778 0.7537378  0.83135812]
 [0.2857884  0.32962358 0.8769639 ]
 [0.62906002 0.78383444 0.95554699]]


In [21]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
c= np.multiply(a,b)
print(c)

[[ 4]
 [10]
 [18]]
